// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: bouncermain/metrics.go
// DO NOT EDIT!

package bouncermain

import (
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

func (mj *Metrics) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if mj == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *Metrics) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if mj == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"nominal":`)
	fflib.FormatBits2(buf, uint64(mj.Nominal), 10, false)
	buf.WriteString(`,"acquired":`)
	fflib.FormatBits2(buf, uint64(mj.Acquired), 10, false)
	buf.WriteString(`,"released":`)
	fflib.FormatBits2(buf, uint64(mj.Released), 10, false)
	buf.WriteString(`,"total_wait_time":`)
	fflib.FormatBits2(buf, uint64(mj.WaitTime), 10, false)
	buf.WriteString(`,"timed_out":`)
	fflib.FormatBits2(buf, uint64(mj.TimedOut), 10, false)
	buf.WriteString(`,"created_at":`)
	fflib.WriteJsonString(buf, string(mj.CreatedAt))
	buf.WriteByte('}')
	return nil
}
